# Every target runs from a fresh clone. The interpreter is pinned to 3.13; pyenv
# picks it up from .python-version, otherwise pass PY=/path/to/python3.13.
PY ?= python3.13
VENV := .venv
PIP := $(VENV)/bin/pip
PYTHON := $(VENV)/bin/python

.PHONY: setup test lint fmt samples verify lock run smoke

setup: $(VENV)/.installed

$(VENV)/.installed: requirements-dev.lock
	$(PY) -m venv $(VENV)
	$(PIP) install --quiet --upgrade pip
	$(PIP) install --quiet --require-hashes -r requirements-dev.lock
	touch $@

test: setup
	$(PYTHON) -m pytest

lint: setup
	$(VENV)/bin/ruff check .
	$(VENV)/bin/ruff format --check .

fmt: setup
	$(VENV)/bin/ruff format .
	$(VENV)/bin/ruff check --fix .

# Regenerates data/synthetic/ from the fixed seed. Byte-identical on one platform; see
# data/synthetic/README.md for why a different platform's wheels may differ by a few bytes.
samples: setup
	$(PYTHON) tools/make_samples.py --out data/synthetic

verify:
	bash verify.sh

# Local dev server — binds 127.0.0.1:8080 (PORT overrides); Ctrl+C to stop.
run: setup
	$(PYTHON) app/server.py

# Starts its own copy of the server, hits GET /health and one POST /inspect, prints the
# decision, shuts down. No AWS, no network beyond 127.0.0.1.
smoke: setup
	$(PYTHON) app/smoke.py

# Rebuilds the hash locks. Needs pip-tools in a throwaway venv; the lock header records the
# generator and its version. Run only when a pin in requirements*.txt changes. pip-tools
# 7.6.1 writes a spurious `--no-index` into the header command (the index was used), so it
# is stripped and the pip-compile version is stamped in its place.
lock:
	$(PY) -m venv .venv-lock
	.venv-lock/bin/pip install --quiet pip-tools
	.venv-lock/bin/pip-compile --quiet --generate-hashes --no-strip-extras --output-file requirements.lock requirements.txt
	.venv-lock/bin/pip-compile --quiet --generate-hashes --no-strip-extras --output-file requirements-dev.lock requirements-dev.txt
	ver="$$(.venv-lock/bin/pip-compile --version | sed 's/,//')"; \
	for f in requirements.lock requirements-dev.lock; do \
	  sed -i.bak -e 's/ --no-index//' -e "2s|.*|# This file is autogenerated by pip-compile with Python 3.13 ($$ver)|" "$$f" && rm -f "$$f.bak"; \
	done
	rm -rf .venv-lock
